apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-insurance
spec:
  serviceName: postgres-insurance
  replicas: 1
  selector:
    matchLabels:
      app: postgres-insurance
  template:
    metadata:
      labels:
        app: postgres-insurance
    spec:
      containers:
      - name: postgres-insurance
        image: postgres:15.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: insurancedb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: '12345'
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi